LineLength:
  Max: 120
ClassVars:
  Enabled: false
Style/RescueModifier:
  Enabled: false
MethodLength:
  Max: 17
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 9
