AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'example/**/*'
LineLength:
  Max: 120
ClassVars:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
MethodLength:
  Max: 18
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 9
Metrics/BlockLength:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
